### ISSUE TITLE
Not an issue but an idea.

### ISSUE THREAD

**Issue by BoomBoom75** [Alee14/YouTube-TV-Client-2.0#12]
Hi Alee,

I just used your program on my RPI4 thinking it was for YouTubeTV, but it was **you tube** that you can watch on a **tv**. I was looking for something for something like this but for YouTubeTV.

Is their a way this can be done by editing/changing your existing code?

**Comment by Alee14** [comment]
I am not sure if it will be possible as YouTube TV (the service) probably isn't remote/controller friendly, which is why I made this client, and it also serves as a user agent spoofer so YouTube thinks the client is running on TV.
